### ISSUE TITLE
This is AWESOME!

### ISSUE THREAD

**Issue by yairEO** [danmarshall/google-font-to-svg-path#10]
Thank you so much for this tool, saved me time dealing with Photoshop annoyances!
such a handy tool, straight to my bookmarks!

**Comment by yairEO** [comment]
Only thing I am missing is font kerning

**Comment by danmarshall** [comment]
Thanks for the feedback! Can you tell me which font this is so I can repro?

**Comment by yairEO** [comment]
It's [Pacifico](https://fonts.google.com/specimen/Pacifico)

**Comment by danmarshall** [comment]
Hi @yairEO - looks like all I needed to do was update my copy of opentype.js 🙃
For verification, I added a `kerning` checkbox, default checked. I don't suppose anyone would ever turn it off, but it demonstrates that its working! Appreciate you making this tool even better!
