### ISSUE TITLE
Build this as an API?

### ISSUE THREAD

**Issue by jalexray** [danmarshall/google-font-to-svg-path#15]
Hey Dan, is there a way to build this as an API?

I sent you an email and am following up here. I'd love to be able to convert SVG text to paths and want to make this into an API, but don't have experience with TypeScript. Are you aware of python bindings for maker.js, or any way that I can tweak this repo to make it into an API?

**Comment by danmarshall** [comment]
Hi @jalexray, I'm not sure exactly how Python works, can you execute a shell command? If so you could run a node.js script. You'd need to pass some parameters on the command line, such as font file path etc.

**Comment by jalexray** [comment]
Yeah, you can run a shell command. Is there documentation on parameters that you could pass to script? For the font file path, is it possible to refer to non-downloaded Google fonts?

**Comment by danmarshall** [comment]
I just found a repo that already does this: https://github.com/jvjc/txt2svg

**Comment by jalexray** [comment]
Wow, thanks! This is awesome.
