### ISSUE TITLE
Fill Path instead of stroke path

### ISSUE THREAD

**Issue by kpomservices** [danmarshall/google-font-to-svg-path#23]
Currently we get the stroke path for the font, is there is any way to get the fill path data?

**Comment by danmarshall** [comment]
Should be easy enough for someone to add 2 color pickers, one for stroke and one for fill. 
Then an input for stroke width and bevel selector.

**Comment by kpomservices** [comment]
Sorry i think i did not give more details to my question.
I will provide more details, so that you can provide help / guidance for this.

Currently for any font i am getting the stroke path
![image](https://user-images.githubusercontent.com/1684160/130782158-f5f855b5-1a7c-4e94-931a-9436250f1806.png)

but what i need is the inner / fill path of the letter
![image](https://user-images.githubusercontent.com/1684160/130782273-37757f09-86ee-4d16-90c1-fcc0cfca65db.png)

Please suggest how to get the fill path?

**Comment by danmarshall** [comment]
If you look at the generated svg, there is currently a `fill="none"` attribute. After you have copied and pasted it, you can change fill to your color. You can also change or remove the stroke color and stroke width attributes.

**Comment by kpomservices** [comment]
@danmarshall, I tried to find the way to get the filled path using paper js / maker js libraries but could not find a solution for this.Please let me know if you can provide or help by providing more direction for this?

**Comment by danmarshall** [comment]
Check out this article: https://css-tricks.com/how-to-get-handwriting-animation-with-irregular-svg-strokes/

**Comment by kpomservices** [comment]
Thx @danmarshall, in this approach they create the paths / mask manually, i want someway to do these steps dynamically.

There are some single line / single stroke fonts which i am trying to use for this 
https://www.quantumenterprises.co.uk/handwriting-fonts/single-line-handwriting-fonts-explanation.htm

**Comment by danmarshall** [comment]
@kpomservices - yes the article uses a manual method. Automating it is the harder issue. Again, I suggest looking at Noah's technique to find the "spine" of a shape" https://observablehq.com/@veltman/centerline-labeling

**Comment by kpomservices** [comment]
Ok Thx.

I tried with single stoke font, but its also showing multiple strokes after getting converted 
![image](https://user-images.githubusercontent.com/1684160/132441868-266dd85f-01eb-48cd-a25a-7782fcf2cc06.png)

I will check centerline-labeling technique.

**Comment by danmarshall** [comment]
Closing this for now, since this library does not provide this functionality. Thanks for bringing it to discussion.
