### ISSUE TITLE
Special symbols like this ★

### ISSUE THREAD

**Issue by erf** [danmarshall/google-font-to-svg-path#26]
Would it be possible to add support for special characters like this star ★ ?
https://unicode-table.com/en/2605/

Or even emojis like this 💀 ?

I guess it depends if the font supports it?

**Comment by danmarshall** [comment]
Hi @erf, for font parsing we depend on [opentype.js](https://opentype.js.org/) which seems to lack features for special characters. There's quite a few open issues with this library: https://github.com/opentypejs/opentype.js/issues
If you know of any other library that supports these symbols please let me know.

**Comment by erf** [comment]
Hi @danmarshall, i was able to create the star ★ using a few fonts, like "Noto Serif JP" or "Zen Antique", but other symbols were missing.

I saw this other library [font-js](https://github.com/hlorenzi/font-js) which might support this?

**Comment by erf** [comment]
It seem advanced symbols are not supported by either packages per now. I'll close this for now as this seem to be blocked by third party dependencies. Feel free to open again.
