### ISSUE TITLE
Command line usage?

### ISSUE THREAD

**Issue by tennessinegd** [danmarshall/google-font-to-svg-path#28]
I need to automatically convert the input text to SVG using a local font file. How could I use this program through the command line instead of using the GUI?

**Comment by danmarshall** [comment]
Hi @tennessinegd , this repo doesn't have a command line option. You might try this library: https://github.com/shrhdk/text-to-svg 

Both this repo and text-to-svg use [opentype.js](https://github.com/opentypejs/opentype.js).

**Comment by tennessinegd** [comment]
Thank you, I'll look into it.
