### ISSUE TITLE
"fill-rule: evenodd" causing holes in glyphs

### ISSUE THREAD

**Issue by joliss** [danmarshall/google-font-to-svg-path#30]
Selecting "Source Code Pro" and Variant 500, and setting Text to "4", there's a hole in the glyph where the strokes overlap:

![4](https://user-images.githubusercontent.com/524783/177408986-88553e66-f528-4c54-af1b-954ed61909a0.svg)

At first blush, this seems to be because the `<g>` element has `fill-rule="evenodd"` set. Changing it to the default `fill-rule="nonzero"` fixes the issue:

![4](https://user-images.githubusercontent.com/524783/177409166-72e41206-680f-41a7-bc2c-817b69429f25.svg)

P.S. Love this tool, thanks for creating it!

**Comment by danmarshall** [comment]
Thanks for pointing this out! It seems that some fonts have degenerate outlines, we should add a `fill-rule` checkbox.
