### ISSUE TITLE
Thank you !

### ISSUE THREAD

**Issue by hrgdavor** [danmarshall/google-font-to-svg-path#34]
I have a lots of ideas and plans, one of which is bringing better support for google fonts and other customs to jscad. In the meantime, I wanted to make sth with few letters quickly, and found this (google ofc). 

Thank you !

**Comment by danmarshall** [comment]
Cheers! 🍻
FYI, this uses Maker.js under the hood 😉

**Comment by hrgdavor** [comment]
I have also discovered 2 bugs in jscad handling of SVG while making this small 3d model (printing a house number plate).

I like maker.js too :)

I would suggest to link to it from this utility or link to a page listing your projects. Personally, if I find a nice utility like this and there are more from same author, I like to check them out :)
