### ISSUE TITLE
Italic and Bold

### ISSUE THREAD

**Issue by Lewiscowles1986** [danmarshall/google-font-to-svg-path#6]
Perhaps a strange one, but is there a way to support bold and italic / emphasis for characters where there is no bold / emphasis? I'm adding a transform skewX for `<em>` (I know that's not ideal, but it seems to work)

**Comment by danmarshall** [comment]
For italic, I suppose that a skew is all you can do. For bold, you may want to try my other project [svg-path-outline](https://github.com/danmarshall/svg-path-outline)
