### ISSUE TITLE
Option for characters as separate groups

### ISSUE THREAD

**Issue by Lewiscowles1986** [danmarshall/google-font-to-svg-path#7]
It would be lovely to separate characters as separate groups.

https://codepen.io/Lewiscowles1986/pen/Naxeda?editors=1000 is what I achieved using your tool in an experiment to not use illustrator (the SVG output seems a lot cleaner).

To achieve this I had to use your tool twice, and use the transform tool to get the text to fit. It works, but I'm wondering if it could be more seamless.

**Comment by danmarshall** [comment]
Ok, I added a new checkbox "separate characters" which will create each character as its own `<path>` element. Thank for the feedback!

**Comment by danmarshall** [comment]
make sure to clear your browser cache to get the changes.

**Comment by Lewiscowles1986** [comment]
thank you, I really wasn't expecting it to be done at all, but thanks

**Comment by danmarshall** [comment]
Luckily it was pretty simple since the backing code already had this concept 😃
