### ISSUE TITLE
Custom Fonts

### ISSUE THREAD

**Issue by hyperpanthera** [danmarshall/google-font-to-svg-path#9]
Amazing stuff, is it possible to add custom fonts like Kiona Regular?

https://www.dafont.com/kiona-2.font

**Comment by danmarshall** [comment]
I suppose there could be an upload button...

**Comment by bruthabryce** [comment]
Hey, Is this being built?

**Comment by danmarshall** [comment]
@bruthabryce not that I'm aware of, but I will gladly take a PR. It shouldn't be too difficult.

**Comment by bruthabryce** [comment]
that would be awesome. What font files do you need from me to build?

**Comment by danmarshall** [comment]
Oh I was thinking more of adding an upload button to the page.

**Comment by bruthabryce** [comment]
ah yea, That would work as well!
